const styles = {
  page: {
    minHeight: "100%",
    background: "radial-gradient(ellipse at top left, #F7EFDD 0%, #F2E8D5 45%, #ECDFC4 100%)",
    fontFamily: "'EB Garamond', Georgia, serif",
    color: "#2B2B2B",
    padding: "0",
    position: "relative",
  },
  container: {
    maxWidth: "780px",
    margin: "0 auto",
    padding: "32px 20px 64px",
  },
  header: {
    textAlign: "center",
    marginBottom: "28px",
    borderBottom: "3px double #8B3A2C",
    paddingBottom: "18px",
  },
  title: {
    fontSize: "2.1rem",
    fontWeight: 700,
    letterSpacing: "0.02em",
    margin: 0,
    color: "#1B3A2F",
  },
  suitRow: {
    fontSize: "1rem",
    letterSpacing: "0.4em",
    marginTop: "6px",
  },
  subtitle: {
    fontFamily: "'Courier Prime', 'Courier New', monospace",
    fontSize: "0.78rem",
    letterSpacing: "0.15em",
    textTransform: "uppercase",
    color: "#6b6457",
    marginTop: "8px",
  },
  card: {
    background: "#FBF6EA",
    border: "1px solid #d9c9a3",
    borderRadius: "4px",
    padding: "24px",
    marginBottom: "20px",
    boxShadow: "0 2px 8px rgba(43,43,43,0.08)",
  },
  label: {
    display: "block",
    fontFamily: "'Courier Prime', 'Courier New', monospace",
    fontSize: "0.72rem",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    color: "#1B3A2F",
    marginBottom: "6px",
    fontWeight: 700,
  },
  input: {
    width: "100%",
    padding: "10px 12px",
    fontSize: "1rem",
    border: "1px solid #c9b896",
    borderRadius: "3px",
    background: "#fff",
    fontFamily: "'EB Garamond', Georgia, serif",
    color: "#2B2B2B",
    boxSizing: "border-box",
  },
  row: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
    marginBottom: "16px",
  },
  btn: {
    background: "#1B3A2F",
    color: "#F2E8D5",
    border: "none",
    borderRadius: "3px",
    padding: "13px 22px",
    fontSize: "0.95rem",
    fontWeight: 700,
    letterSpacing: "0.04em",
    cursor: "pointer",
    fontFamily: "'Courier Prime', 'Courier New', monospace",
    textTransform: "uppercase",
    width: "100%",
  },
  btnSecondary: {
    background: "transparent",
    color: "#8B3A2C",
    border: "1.5px solid #8B3A2C",
    borderRadius: "3px",
    padding: "11px 18px",
    fontSize: "0.85rem",
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "'Courier Prime', 'Courier New', monospace",
    textTransform: "uppercase",
    letterSpacing: "0.03em",
  },
  ledger: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 0,
    border: "1px solid #1B3A2F",
    borderRadius: "4px",
    overflow: "hidden",
    marginBottom: "20px",
  },
  ledgerCol: {
    padding: "20px",
    textAlign: "center",
  },
  ledgerColA: {
    background: "#1B3A2F",
    color: "#F2E8D5",
    borderRight: "2px solid #C9A24B",
  },
  ledgerColB: {
    background: "#2c4a3d",
    color: "#F2E8D5",
  },
  teamName: {
    fontFamily: "'Courier Prime', 'Courier New', monospace",
    fontSize: "0.75rem",
    letterSpacing: "0.15em",
    textTransform: "uppercase",
    opacity: 0.8,
    marginBottom: "4px",
  },
  teamScore: {
    fontSize: "2.6rem",
    fontWeight: 700,
    fontFamily: "'Courier Prime', 'Courier New', monospace",
    color: "#C9A24B",
  },
  error: {
    background: "#f8e2dd",
    border: "1px solid #8B3A2C",
    color: "#7a2e1f",
    padding: "10px 14px",
    borderRadius: "3px",
    fontSize: "0.88rem",
    marginBottom: "16px",
    fontFamily: "'Courier Prime', 'Courier New', monospace",
  },
  historyRow: {
    display: "grid",
    gridTemplateColumns: "32px 1fr 70px 70px",
    gap: "10px",
    alignItems: "center",
    padding: "10px 4px",
    borderBottom: "1px solid #e3d6b3",
    fontSize: "0.88rem",
  },
  historyNum: {
    fontFamily: "'Courier Prime', 'Courier New', monospace",
    color: "#a89770",
    fontWeight: 700,
  },
  historyScore: {
    fontFamily: "'Courier Prime', 'Courier New', monospace",
    textAlign: "right",
    fontWeight: 700,
  },
  toggleGroup: {
    display: "flex",
    gap: "10px",
  },
  toggleBtn: (active) => ({
    flex: 1,
    padding: "12px",
    borderRadius: "3px",
    border: active ? "2px solid #1B3A2F" : "1px solid #c9b896",
    background: active ? "#1B3A2F" : "#fff",
    color: active ? "#F2E8D5" : "#2B2B2B",
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "'Courier Prime', 'Courier New', monospace",
    fontSize: "0.85rem",
  }),
  checkboxRow: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "12px 14px",
    background: "#FBF6EA",
    border: "1px solid #c9b896",
    borderRadius: "3px",
    marginBottom: "16px",
  },
  hint: {
    fontSize: "0.78rem",
    color: "#8a7d5e",
    marginTop: "4px",
    fontStyle: "italic",
  },
};

export default styles;